DELETE FROM CRAWLING_INFO WHERE 1;

INSERT INTO CRAWLING_INFO (NEWS_KEYWORD, STOCK_NAME, STOCK_TYPE) VALUES ('삼성전자', '삼성전자', 'korea');
INSERT INTO CRAWLING_INFO (NEWS_KEYWORD, STOCK_NAME, STOCK_TYPE) VALUES ('LG디스플레이', 'LG디스플레이', 'korea');
INSERT INTO CRAWLING_INFO (NEWS_KEYWORD, STOCK_NAME, STOCK_TYPE) VALUES ('애플', 'AAPL', 'us');
INSERT INTO CRAWLING_INFO (NEWS_KEYWORD, STOCK_NAME, STOCK_TYPE) VALUES ('엔비디아', 'NVDA', 'us');